version: 2

models:

  - name: fact_enrollments
    description: "Faits des inscriptions étudiants aux cours"
    columns:
      - name: enrollment_key
        description: "Identifiant unique de l'inscription"
        tests:
          - not_null
          - unique

      - name: student_key
        description: "Doit exister dans dim_student"
        tests:
          - not_null
          - relationships:
              to: ref('dim_student')
              field: student_id

      - name: course_key
        description: "Doit exister dans dim_course"
        tests:
          - not_null
          - relationships:
              to: ref('dim_course')
              field: course_id

      - name: status
        description: "Statut de l'inscription"
        tests:
          - accepted_values:
              values: ['active', 'inactive', 'completed', 'cancelled', 'unknown']

  - name: fact_interactions
    description: "Faits des interactions CRM avec les contacts"
    columns:
      - name: interaction_id
        description: "Identifiant unique de l'interaction"
        tests:
          - not_null
          - unique

      - name: contact_id
        description: "Doit exister dans dim_contact"
        tests:
          - not_null
          - relationships:
              to: ref('dim_contact')
              field: contact_id

      - name: interaction_type
        description: "Type d'interaction (standardisé)"
        tests:
          - accepted_values:
              values: ['call', 'email', 'meeting', 'appointment', 'unknown']
